version: '3.3'

services:
   acloudbank-core:
     image: acloudbank-core
     build:
       dockerfile: ./Dockerfile
       context: .
     platform: linux/amd64
     ports:
       - "127.0.0.1:8090:8090"
     networks:
       - docker-elk_el
     
    # command: >
    #   /bin/bash -c "/usr/local/bin/witness_node --rpc-endpoint=127.0.0.1:8090 --plugins=\"witness api_helper_indexes market_history elasticsearch es_objects\" --elasticsearch-node-url=http://elasticsearch:9200/ --elasticsearch-index-prefix=\"search-rsquared-\" --elasticsearch-visitor=true --elasticsearch-basic-auth=\"elastic:changeme\" --es-objects-elasticsearch-url=http://elasticsearch:9200/ --es-objects-auth=\"elastic:changeme\""

    # command: >
    #   tail -f /dev/null

     volumes:
       - /var/docker/bts/data:/data
     command: "/bitshares/programs/cli_wallet/cli_wallet -s ws://127.0.0.1:8090 -H 0.0.0.0:8090 -d"

#services:
#  acloudbank-core:
#    image: docker.io/lunacrafts/indexer-rsquared:latest
#    platform: linux/amd64
#    ports:
#      - "8090:8090"
#    networks:
#      - docker-elk_el
#    command: >
#      /bin/bash -c "/usr/local/bin/witness_node --rpc-endpoint=127.0.0.1:8090 --plugins=\"witness api_helper_indexes market_history elasticsearch es_objects\" --elasticsearch-node-url=http://elasticsearch:9200/ --elasticsearch-index-prefix=\"search-rsquared-\" --elasticsearch-visitor=true --elasticsearch-basic-auth=\"elastic:changeme\" --es-objects-elasticsearch-url=http://elasticsearch:9200/ --es-objects-auth=\"elastic:changeme\""

networks:
  docker-elk_el:
    external: false